 hosts: webservers
  become: yes
  tasks:
  - name: Reiniciar todos los servidores Web
    apt: name=apache2 state=latest
  - name: verificar apache
    service: name=apache2 state=started enabled=yes

  - name: add grafana gpg key
    shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

  - name: add grafana repositorio
    apt_repository:
     repo: deb https://packages.grafana.com/oss/deb stable main
     state: present
     filename: grafana

  - name: Install grafana
    apt:
        name: grafana
        state: present
        update_cache: yes

  - name: Enable and start grafana service
    service:
           name: grafana-server
           enabled: yes
           state: started
  - name: Install necesary package
    apt:
        name: apt-transport-https
        state: present
        update_cache: yes
